// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShowHashFileNew;

#nullable disable

namespace ShowHashFileNew.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220918025813_h5")]
    partial class h5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShowHashFileNew.Meteostation", b =>
                {
                    b.Property<int>("Idmeteostation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("admin_code")
                        .HasColumnType("int");

                    b.Property<string>("alt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("lat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("lon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("station")
                        .HasColumnType("int");

                    b.HasKey("Idmeteostation");

                    b.ToTable("Meteostations1");
                });
#pragma warning restore 612, 618
        }
    }
}
