// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShowHashFileNew;

#nullable disable

namespace ShowHashFileNew.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShowHashFileNew.Fileyandex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("content_error")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("contentrf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("fileyandex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("iditem")
                        .HasColumnType("int");

                    b.Property<int>("idymail")
                        .HasColumnType("int");

                    b.Property<string>("md5yandex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("mime_typeyandex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nameyandex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("pathyandex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("sha256yandex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("sizeyandex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Fileyandex1s");
                });

            modelBuilder.Entity("ShowHashFileNew.Meteostation", b =>
                {
                    b.Property<int>("Idmeteostation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("admin_code")
                        .HasColumnType("int");

                    b.Property<string>("alt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("lat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("lon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("station")
                        .HasColumnType("int");

                    b.HasKey("Idmeteostation");

                    b.ToTable("Meteostations1");
                });
#pragma warning restore 612, 618
        }
    }
}
